# Generated by Django 5.1.6 on 2025-06-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataLatih',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('hari', models.IntegerField(choices=[(1, 'Senin'), (2, 'Selasa'), (3, 'Rabu'), (4, 'Kamis'), (5, 'Jumat'), (6, 'Sabtu'), (7, 'Minggu')])),
                ('waktu', models.IntegerField(choices=[(1, 'Pagi'), (2, 'Siang'), (3, 'Sore'), (4, 'Malam')])),
                ('durasi', models.IntegerField()),
                ('paket', models.IntegerField(choices=[(0, 'Reguler'), (1, 'Intensif'), (2, 'Private'), (3, 'VIP')])),
                ('status', models.CharField(choices=[('Bisa', 'Bisa'), ('Tidak Bisa', 'Tidak Bisa')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DataUji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('hari', models.IntegerField(choices=[(1, 'Senin'), (2, 'Selasa'), (3, 'Rabu'), (4, 'Kamis'), (5, 'Jumat'), (6, 'Sabtu'), (7, 'Minggu')])),
                ('waktu', models.IntegerField(choices=[(1, 'Pagi'), (2, 'Siang'), (3, 'Sore'), (4, 'Malam')])),
                ('durasi', models.IntegerField()),
                ('paket', models.IntegerField(choices=[(0, 'Reguler'), (1, 'Intensif'), (2, 'Private'), (3, 'VIP')])),
                ('hasil_prediksi', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
